import Header from '@/components/header';
import ThemeProvider from '@/components/theme-provider';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: `VeriDocx`,
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="min-h-screen  w-full bg-background font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav>
            <Header />
          </nav>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
