import Header from '@/components/header';
import ThemeProvider from '@/components/theme-provider';
import "@/styles/globals.css";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: `Sign In`,
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header />
        <main className="min-h-full min-w-full md:px-[6vw]">
          {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
